spring.application.name=demo
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres.mjowsnxbjeqnpyormvko}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optimizacion de conexion para Supabase Pooler (evita desconexiones por inactividad)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=20000

